M48
; DRILL file {KiCad 8.0.5} date 2025-03-11T15:07:14+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-11T15:07:14+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.7432Y-4.396
X7.1035Y-4.396
T2
X4.0626Y-4.6011
X6.7606Y-3.8211
X7.9506Y-4.6041
M30
